# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quick_spec.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QuickSpec(object):
    def setupUi(self, QuickSpec):
        QuickSpec.setObjectName("QuickSpec")
        QuickSpec.resize(907, 830)
        self.centralwidget = QtWidgets.QWidget(QuickSpec)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.clickNormalButton = QtWidgets.QPushButton(self.centralwidget)
        self.clickNormalButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clickNormalButton.sizePolicy().hasHeightForWidth())
        self.clickNormalButton.setSizePolicy(sizePolicy)
        self.clickNormalButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clickNormalButton.setCheckable(True)
        self.clickNormalButton.setAutoExclusive(True)
        self.clickNormalButton.setObjectName("clickNormalButton")
        self.horizontalLayout_4.addWidget(self.clickNormalButton)
        self.zoomButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomButton.sizePolicy().hasHeightForWidth())
        self.zoomButton.setSizePolicy(sizePolicy)
        self.zoomButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zoomButton.setCheckable(True)
        self.zoomButton.setAutoExclusive(True)
        self.zoomButton.setObjectName("zoomButton")
        self.horizontalLayout_4.addWidget(self.zoomButton)
        self.panButton = QtWidgets.QPushButton(self.centralwidget)
        self.panButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panButton.sizePolicy().hasHeightForWidth())
        self.panButton.setSizePolicy(sizePolicy)
        self.panButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.panButton.setCheckable(True)
        self.panButton.setAutoExclusive(True)
        self.panButton.setObjectName("panButton")
        self.horizontalLayout_4.addWidget(self.panButton)
        self.zoomResetButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomResetButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomResetButton.sizePolicy().hasHeightForWidth())
        self.zoomResetButton.setSizePolicy(sizePolicy)
        self.zoomResetButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zoomResetButton.setObjectName("zoomResetButton")
        self.horizontalLayout_4.addWidget(self.zoomResetButton)
        self.undoButton = QtWidgets.QPushButton(self.centralwidget)
        self.undoButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.undoButton.sizePolicy().hasHeightForWidth())
        self.undoButton.setSizePolicy(sizePolicy)
        self.undoButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.undoButton.setObjectName("undoButton")
        self.horizontalLayout_4.addWidget(self.undoButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pathLabel = QtWidgets.QLabel(self.centralwidget)
        self.pathLabel.setText("")
        self.pathLabel.setObjectName("pathLabel")
        self.horizontalLayout.addWidget(self.pathLabel)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.middlePlot = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middlePlot.sizePolicy().hasHeightForWidth())
        self.middlePlot.setSizePolicy(sizePolicy)
        self.middlePlot.setTitle("")
        self.middlePlot.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.middlePlot.setFlat(False)
        self.middlePlot.setObjectName("middlePlot")
        self.gridLayout.addWidget(self.middlePlot, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 2, 1, 1)
        QuickSpec.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(QuickSpec)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 907, 21))
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        QuickSpec.setMenuBar(self.menuBar)
        self.actionLoad_Spec = QtWidgets.QAction(QuickSpec)
        self.actionLoad_Spec.setObjectName("actionLoad_Spec")
        self.actionSave_as_png = QtWidgets.QAction(QuickSpec)
        self.actionSave_as_png.setEnabled(False)
        self.actionSave_as_png.setObjectName("actionSave_as_png")
        self.actionReset_window = QtWidgets.QAction(QuickSpec)
        self.actionReset_window.setObjectName("actionReset_window")
        self.actionClear_last_fitted_model = QtWidgets.QAction(QuickSpec)
        self.actionClear_last_fitted_model.setObjectName("actionClear_last_fitted_model")
        self.actionClear_fitted_models = QtWidgets.QAction(QuickSpec)
        self.actionClear_fitted_models.setObjectName("actionClear_fitted_models")
        self.actionShow_fitted_data_parameters = QtWidgets.QAction(QuickSpec)
        self.actionShow_fitted_data_parameters.setObjectName("actionShow_fitted_data_parameters")
        self.actionSave_fitted_data_from_model = QtWidgets.QAction(QuickSpec)
        self.actionSave_fitted_data_from_model.setObjectName("actionSave_fitted_data_from_model")
        self.menuFile.addAction(self.actionLoad_Spec)
        self.menuFile.addAction(self.actionSave_as_png)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(QuickSpec)
        QtCore.QMetaObject.connectSlotsByName(QuickSpec)

    def retranslateUi(self, QuickSpec):
        _translate = QtCore.QCoreApplication.translate
        QuickSpec.setWindowTitle(_translate("QuickSpec", "QuickSpec"))
        self.clickNormalButton.setText(_translate("QuickSpec", "Click"))
        self.zoomButton.setText(_translate("QuickSpec", "Zoom"))
        self.panButton.setText(_translate("QuickSpec", "Pan"))
        self.zoomResetButton.setText(_translate("QuickSpec", "Zoom reset"))
        self.undoButton.setText(_translate("QuickSpec", "Undo last zoom"))
        self.menuFile.setTitle(_translate("QuickSpec", "File"))
        self.actionLoad_Spec.setText(_translate("QuickSpec", "Load Spectrum/Spectra"))
        self.actionSave_as_png.setText(_translate("QuickSpec", "Save as png"))
        self.actionReset_window.setText(_translate("QuickSpec", "Reset window"))
        self.actionClear_last_fitted_model.setText(_translate("QuickSpec", "Clear last fitted model"))
        self.actionClear_fitted_models.setText(_translate("QuickSpec", "Clear fitted models"))
        self.actionShow_fitted_data_parameters.setText(_translate("QuickSpec", "Show fitted data parameters"))
        self.actionSave_fitted_data_from_model.setText(_translate("QuickSpec", "Save fitted data from model"))

