# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mrs_spec_chan.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MrsSpecChan(object):
    def setupUi(self, MrsSpecChan):
        MrsSpecChan.setObjectName("MrsSpecChan")
        MrsSpecChan.resize(825, 839)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MrsSpecChan.sizePolicy().hasHeightForWidth())
        MrsSpecChan.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MrsSpecChan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bottomChanData = QtWidgets.QGroupBox(self.centralwidget)
        self.bottomChanData.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomChanData.sizePolicy().hasHeightForWidth())
        self.bottomChanData.setSizePolicy(sizePolicy)
        self.bottomChanData.setObjectName("bottomChanData")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.bottomChanData)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mrsCheckbox = QtWidgets.QCheckBox(self.bottomChanData)
        self.mrsCheckbox.setObjectName("mrsCheckbox")
        self.horizontalLayout_3.addWidget(self.mrsCheckbox)
        self.nirSpecCheckbox = QtWidgets.QCheckBox(self.bottomChanData)
        self.nirSpecCheckbox.setObjectName("nirSpecCheckbox")
        self.horizontalLayout_3.addWidget(self.nirSpecCheckbox)
        self.nirSpecGapCheckbox = QtWidgets.QCheckBox(self.bottomChanData)
        self.nirSpecGapCheckbox.setObjectName("nirSpecGapCheckbox")
        self.horizontalLayout_3.addWidget(self.nirSpecGapCheckbox)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.bottomChanData, 4, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lambdaLabel = QtWidgets.QLabel(self.groupBox_4)
        self.lambdaLabel.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lambdaLabel.sizePolicy().hasHeightForWidth())
        self.lambdaLabel.setSizePolicy(sizePolicy)
        self.lambdaLabel.setObjectName("lambdaLabel")
        self.horizontalLayout.addWidget(self.lambdaLabel)
        self.lambdaEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lambdaEdit.setEnabled(False)
        self.lambdaEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.lambdaEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lambdaEdit.setObjectName("lambdaEdit")
        self.horizontalLayout.addWidget(self.lambdaEdit)
        self.zLabel = QtWidgets.QLabel(self.groupBox_4)
        self.zLabel.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zLabel.sizePolicy().hasHeightForWidth())
        self.zLabel.setSizePolicy(sizePolicy)
        self.zLabel.setObjectName("zLabel")
        self.horizontalLayout.addWidget(self.zLabel)
        self.zEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.zEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zEdit.sizePolicy().hasHeightForWidth())
        self.zEdit.setSizePolicy(sizePolicy)
        self.zEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.zEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.zEdit.setObjectName("zEdit")
        self.horizontalLayout.addWidget(self.zEdit, 0, QtCore.Qt.AlignLeft)
        self.loadOpWavelengthButton = QtWidgets.QPushButton(self.groupBox_4)
        self.loadOpWavelengthButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadOpWavelengthButton.sizePolicy().hasHeightForWidth())
        self.loadOpWavelengthButton.setSizePolicy(sizePolicy)
        self.loadOpWavelengthButton.setObjectName("loadOpWavelengthButton")
        self.horizontalLayout.addWidget(self.loadOpWavelengthButton, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.loadSpectra = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadSpectra.sizePolicy().hasHeightForWidth())
        self.loadSpectra.setSizePolicy(sizePolicy)
        self.loadSpectra.setObjectName("loadSpectra")
        self.horizontalLayout_8.addWidget(self.loadSpectra)
        self.loadLoi = QtWidgets.QPushButton(self.groupBox_5)
        self.loadLoi.setEnabled(False)
        self.loadLoi.setObjectName("loadLoi")
        self.horizontalLayout_8.addWidget(self.loadLoi)
        self.loadTemplate = QtWidgets.QPushButton(self.groupBox_5)
        self.loadTemplate.setObjectName("loadTemplate")
        self.horizontalLayout_8.addWidget(self.loadTemplate)
        self.saveButton = QtWidgets.QPushButton(self.groupBox_5)
        self.saveButton.setEnabled(False)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_8.addWidget(self.saveButton)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.gridLayout.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.middlePlot = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middlePlot.sizePolicy().hasHeightForWidth())
        self.middlePlot.setSizePolicy(sizePolicy)
        self.middlePlot.setMaximumSize(QtCore.QSize(16777215, 500))
        self.middlePlot.setTitle("")
        self.middlePlot.setObjectName("middlePlot")
        self.gridLayout.addWidget(self.middlePlot, 3, 0, 1, 1)
        self.spectraData = QtWidgets.QGroupBox(self.centralwidget)
        self.spectraData.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectraData.sizePolicy().hasHeightForWidth())
        self.spectraData.setSizePolicy(sizePolicy)
        self.spectraData.setObjectName("spectraData")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.spectraData)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.spectraListWidget = QtWidgets.QListWidget(self.spectraData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectraListWidget.sizePolicy().hasHeightForWidth())
        self.spectraListWidget.setSizePolicy(sizePolicy)
        self.spectraListWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.spectraListWidget.setObjectName("spectraListWidget")
        self.horizontalLayout_5.addWidget(self.spectraListWidget)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.gridLayout.addWidget(self.spectraData, 2, 0, 1, 1)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout.addWidget(self.clearButton, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MrsSpecChan.setCentralWidget(self.centralwidget)

        self.retranslateUi(MrsSpecChan)
        QtCore.QMetaObject.connectSlotsByName(MrsSpecChan)

    def retranslateUi(self, MrsSpecChan):
        _translate = QtCore.QCoreApplication.translate
        MrsSpecChan.setWindowTitle(_translate("MrsSpecChan", "MrsSpecChan - Beta version"))
        self.bottomChanData.setTitle(_translate("MrsSpecChan", "Areas"))
        self.mrsCheckbox.setText(_translate("MrsSpecChan", "MRS"))
        self.nirSpecCheckbox.setText(_translate("MrsSpecChan", "NIRSpec"))
        self.nirSpecGapCheckbox.setText(_translate("MrsSpecChan", "NIRSpec Gap"))
        self.lambdaLabel.setText(_translate("MrsSpecChan", "TextLabel"))
        self.zLabel.setText(_translate("MrsSpecChan", "z:"))
        self.loadOpWavelengthButton.setText(_translate("MrsSpecChan", "Load optional wavelengths values"))
        self.loadSpectra.setText(_translate("MrsSpecChan", "Load spectra"))
        self.loadLoi.setText(_translate("MrsSpecChan", "Load loi"))
        self.loadTemplate.setText(_translate("MrsSpecChan", "Load template"))
        self.saveButton.setText(_translate("MrsSpecChan", "Save as png"))
        self.spectraData.setTitle(_translate("MrsSpecChan", "Data"))
        self.clearButton.setText(_translate("MrsSpecChan", "Clear all"))
