# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ellipseCreation.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ellipseCreation(object):
    def setupUi(self, ellipseCreation):
        ellipseCreation.setObjectName("ellipseCreation")
        ellipseCreation.resize(550, 150)
        ellipseCreation.setMinimumSize(QtCore.QSize(550, 150))
        self.gridLayout_2 = QtWidgets.QGridLayout(ellipseCreation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.aAxisLineEdit = QtWidgets.QLineEdit(ellipseCreation)
        self.aAxisLineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.aAxisLineEdit.setObjectName("aAxisLineEdit")
        self.gridLayout.addWidget(self.aAxisLineEdit, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(ellipseCreation)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(ellipseCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.bAxisLineEdit = QtWidgets.QLineEdit(ellipseCreation)
        self.bAxisLineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.bAxisLineEdit.setObjectName("bAxisLineEdit")
        self.gridLayout.addWidget(self.bAxisLineEdit, 5, 3, 1, 1)
        self.label = QtWidgets.QLabel(ellipseCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.createButton = QtWidgets.QPushButton(ellipseCreation)
        self.createButton.setObjectName("createButton")
        self.gridLayout.addWidget(self.createButton, 6, 0, 1, 4)
        self.centerYLineEdit = QtWidgets.QLineEdit(ellipseCreation)
        self.centerYLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.centerYLineEdit.setObjectName("centerYLineEdit")
        self.gridLayout.addWidget(self.centerYLineEdit, 4, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(ellipseCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(ellipseCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.centerXLineEdit = QtWidgets.QLineEdit(ellipseCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerXLineEdit.sizePolicy().hasHeightForWidth())
        self.centerXLineEdit.setSizePolicy(sizePolicy)
        self.centerXLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.centerXLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.centerXLineEdit.setObjectName("centerXLineEdit")
        self.gridLayout.addWidget(self.centerXLineEdit, 4, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(ellipseCreation)
        QtCore.QMetaObject.connectSlotsByName(ellipseCreation)

    def retranslateUi(self, ellipseCreation):
        _translate = QtCore.QCoreApplication.translate
        ellipseCreation.setWindowTitle(_translate("ellipseCreation", "ellipseCreation"))
        self.label_5.setText(_translate("ellipseCreation", "Axis b (Minor Axis)"))
        self.label_3.setText(_translate("ellipseCreation", "Axis a (Major axis)"))
        self.label.setText(_translate("ellipseCreation", "Write the parameters to create the ellipse"))
        self.createButton.setText(_translate("ellipseCreation", "Create ellipse"))
        self.label_7.setText(_translate("ellipseCreation", "Center Y"))
        self.label_6.setText(_translate("ellipseCreation", "Center X"))

