# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rectangleCreation.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_rectangleCreation(object):
    def setupUi(self, rectangleCreation):
        rectangleCreation.setObjectName("rectangleCreation")
        rectangleCreation.resize(475, 210)
        rectangleCreation.setMinimumSize(QtCore.QSize(475, 210))
        self.gridLayout_2 = QtWidgets.QGridLayout(rectangleCreation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(rectangleCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.centerXLineEdit = QtWidgets.QLineEdit(rectangleCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerXLineEdit.sizePolicy().hasHeightForWidth())
        self.centerXLineEdit.setSizePolicy(sizePolicy)
        self.centerXLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.centerXLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.centerXLineEdit.setObjectName("centerXLineEdit")
        self.gridLayout.addWidget(self.centerXLineEdit, 3, 1, 1, 1)
        self.widthLineEdit = QtWidgets.QLineEdit(rectangleCreation)
        self.widthLineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.widthLineEdit.setObjectName("widthLineEdit")
        self.gridLayout.addWidget(self.widthLineEdit, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(rectangleCreation)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(rectangleCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(rectangleCreation)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 2, 1, 1)
        self.bottomLeftYLineEdit = QtWidgets.QLineEdit(rectangleCreation)
        self.bottomLeftYLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bottomLeftYLineEdit.setObjectName("bottomLeftYLineEdit")
        self.gridLayout.addWidget(self.bottomLeftYLineEdit, 4, 3, 1, 1)
        self.heightLineEdit = QtWidgets.QLineEdit(rectangleCreation)
        self.heightLineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.heightLineEdit.setObjectName("heightLineEdit")
        self.gridLayout.addWidget(self.heightLineEdit, 5, 3, 1, 1)
        self.label = QtWidgets.QLabel(rectangleCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.createCenterButton = QtWidgets.QPushButton(rectangleCreation)
        self.createCenterButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createCenterButton.sizePolicy().hasHeightForWidth())
        self.createCenterButton.setSizePolicy(sizePolicy)
        self.createCenterButton.setMinimumSize(QtCore.QSize(0, 0))
        self.createCenterButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.createCenterButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.createCenterButton.setAcceptDrops(False)
        self.createCenterButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.createCenterButton.setAutoFillBackground(False)
        self.createCenterButton.setDefault(False)
        self.createCenterButton.setFlat(False)
        self.createCenterButton.setObjectName("createCenterButton")
        self.gridLayout.addWidget(self.createCenterButton, 6, 0, 1, 2)
        self.createBottomButton = QtWidgets.QPushButton(rectangleCreation)
        self.createBottomButton.setEnabled(True)
        self.createBottomButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.createBottomButton.setObjectName("createBottomButton")
        self.gridLayout.addWidget(self.createBottomButton, 6, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(rectangleCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.centerYLineEdit = QtWidgets.QLineEdit(rectangleCreation)
        self.centerYLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.centerYLineEdit.setObjectName("centerYLineEdit")
        self.gridLayout.addWidget(self.centerYLineEdit, 4, 1, 1, 1)
        self.bottomLeftXLineEdit = QtWidgets.QLineEdit(rectangleCreation)
        self.bottomLeftXLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bottomLeftXLineEdit.setObjectName("bottomLeftXLineEdit")
        self.gridLayout.addWidget(self.bottomLeftXLineEdit, 3, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(rectangleCreation)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(rectangleCreation)
        QtCore.QMetaObject.connectSlotsByName(rectangleCreation)

    def retranslateUi(self, rectangleCreation):
        _translate = QtCore.QCoreApplication.translate
        rectangleCreation.setWindowTitle(_translate("rectangleCreation", "rectangleCreation"))
        self.label_6.setText(_translate("rectangleCreation", "Center X"))
        self.label_5.setText(_translate("rectangleCreation", "Height"))
        self.label_3.setText(_translate("rectangleCreation", "Width"))
        self.label_4.setText(_translate("rectangleCreation", "Bottom Left Y"))
        self.label.setText(_translate("rectangleCreation", "Write the parameters to create the rectangle"))
        self.createCenterButton.setText(_translate("rectangleCreation", "Create rectangle \n"
"with center coordinates"))
        self.createBottomButton.setText(_translate("rectangleCreation", "Create rectangle \n"
"with bottom coordinates"))
        self.label_7.setText(_translate("rectangleCreation", "Center Y"))
        self.label_2.setText(_translate("rectangleCreation", "Bottom Left X"))

