# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectrumVisualization.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_spectrumVisualization(object):
    def setupUi(self, spectrumVisualization):
        spectrumVisualization.setObjectName("spectrumVisualization")
        spectrumVisualization.resize(788, 620)
        self.gridLayout_2 = QtWidgets.QGridLayout(spectrumVisualization)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.moveRangeButton = QtWidgets.QToolButton(spectrumVisualization)
        self.moveRangeButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveRangeButton.sizePolicy().hasHeightForWidth())
        self.moveRangeButton.setSizePolicy(sizePolicy)
        self.moveRangeButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.moveRangeButton.setCheckable(True)
        self.moveRangeButton.setObjectName("moveRangeButton")
        self.gridLayout.addWidget(self.moveRangeButton, 1, 1, 1, 1)
        self.createRangeButton = QtWidgets.QToolButton(spectrumVisualization)
        self.createRangeButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createRangeButton.sizePolicy().hasHeightForWidth())
        self.createRangeButton.setSizePolicy(sizePolicy)
        self.createRangeButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.createRangeButton.setCheckable(True)
        self.createRangeButton.setObjectName("createRangeButton")
        self.gridLayout.addWidget(self.createRangeButton, 1, 0, 1, 1)
        self.loadButton = QtWidgets.QPushButton(spectrumVisualization)
        self.loadButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadButton.sizePolicy().hasHeightForWidth())
        self.loadButton.setSizePolicy(sizePolicy)
        self.loadButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout.addWidget(self.loadButton, 4, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(spectrumVisualization)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.spectrumLayout_vbox = QtWidgets.QVBoxLayout()
        self.spectrumLayout_vbox.setObjectName("spectrumLayout_vbox")
        self.verticalLayout_2.addLayout(self.spectrumLayout_vbox)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 3)
        self.rangeImageButton = QtWidgets.QPushButton(spectrumVisualization)
        self.rangeImageButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangeImageButton.sizePolicy().hasHeightForWidth())
        self.rangeImageButton.setSizePolicy(sizePolicy)
        self.rangeImageButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rangeImageButton.setObjectName("rangeImageButton")
        self.gridLayout.addWidget(self.rangeImageButton, 3, 0, 1, 3)
        self.savePNGButton = QtWidgets.QPushButton(spectrumVisualization)
        self.savePNGButton.setEnabled(False)
        self.savePNGButton.setObjectName("savePNGButton")
        self.gridLayout.addWidget(self.savePNGButton, 2, 1, 1, 1)
        self.saveTextButton = QtWidgets.QPushButton(spectrumVisualization)
        self.saveTextButton.setEnabled(False)
        self.saveTextButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.saveTextButton.setObjectName("saveTextButton")
        self.gridLayout.addWidget(self.saveTextButton, 2, 0, 1, 1)
        self.zoomResetButton = QtWidgets.QPushButton(spectrumVisualization)
        self.zoomResetButton.setEnabled(False)
        self.zoomResetButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zoomResetButton.setObjectName("zoomResetButton")
        self.gridLayout.addWidget(self.zoomResetButton, 5, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(spectrumVisualization)
        QtCore.QMetaObject.connectSlotsByName(spectrumVisualization)

    def retranslateUi(self, spectrumVisualization):
        _translate = QtCore.QCoreApplication.translate
        spectrumVisualization.setWindowTitle(_translate("spectrumVisualization", "spectrumVisualization"))
        self.moveRangeButton.setText(_translate("spectrumVisualization", "Move range area for collapse image"))
        self.createRangeButton.setText(_translate("spectrumVisualization", "Select area for collapse image"))
        self.loadButton.setText(_translate("spectrumVisualization", "Load spectrum on fitLine"))
        self.rangeImageButton.setText(_translate("spectrumVisualization", "Show image from wavelength range"))
        self.savePNGButton.setText(_translate("spectrumVisualization", "Save as png"))
        self.saveTextButton.setText(_translate("spectrumVisualization", "Save spectra as txt"))
        self.zoomResetButton.setText(_translate("spectrumVisualization", "Zoom reset"))

