# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectrumParametersSelection.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_spectrumParametersSelection(object):
    def setupUi(self, spectrumParametersSelection):
        spectrumParametersSelection.setObjectName("spectrumParametersSelection")
        spectrumParametersSelection.resize(526, 114)
        self.gridLayout_2 = QtWidgets.QGridLayout(spectrumParametersSelection)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.fUnitsCombobox = QtWidgets.QComboBox(spectrumParametersSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fUnitsCombobox.sizePolicy().hasHeightForWidth())
        self.fUnitsCombobox.setSizePolicy(sizePolicy)
        self.fUnitsCombobox.setObjectName("fUnitsCombobox")
        self.fUnitsCombobox.addItem("")
        self.fUnitsCombobox.addItem("")
        self.fUnitsCombobox.addItem("")
        self.fUnitsCombobox.addItem("")
        self.fUnitsCombobox.addItem("")
        self.fUnitsCombobox.addItem("")
        self.fUnitsCombobox.addItem("")
        self.fUnitsCombobox.addItem("")
        self.gridLayout.addWidget(self.fUnitsCombobox, 2, 3, 1, 1)
        self.wUnitsCombobox = QtWidgets.QComboBox(spectrumParametersSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wUnitsCombobox.sizePolicy().hasHeightForWidth())
        self.wUnitsCombobox.setSizePolicy(sizePolicy)
        self.wUnitsCombobox.setObjectName("wUnitsCombobox")
        self.wUnitsCombobox.addItem("")
        self.wUnitsCombobox.addItem("")
        self.wUnitsCombobox.addItem("")
        self.gridLayout.addWidget(self.wUnitsCombobox, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(spectrumParametersSelection)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(spectrumParametersSelection)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.redshiftLineEdit = QtWidgets.QLineEdit(spectrumParametersSelection)
        self.redshiftLineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.redshiftLineEdit.setObjectName("redshiftLineEdit")
        self.gridLayout.addWidget(self.redshiftLineEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(spectrumParametersSelection)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(spectrumParametersSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(spectrumParametersSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 3, 0, 1, 2)
        self.acceptButton = QtWidgets.QPushButton(spectrumParametersSelection)
        self.acceptButton.setEnabled(True)
        self.acceptButton.setObjectName("acceptButton")
        self.gridLayout.addWidget(self.acceptButton, 3, 2, 1, 2)
        self.pathLabel = QtWidgets.QLabel(spectrumParametersSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLabel.sizePolicy().hasHeightForWidth())
        self.pathLabel.setSizePolicy(sizePolicy)
        self.pathLabel.setText("")
        self.pathLabel.setObjectName("pathLabel")
        self.gridLayout.addWidget(self.pathLabel, 0, 1, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(spectrumParametersSelection)
        self.acceptButton.clicked.connect(spectrumParametersSelection.accept)
        self.cancelButton.clicked.connect(spectrumParametersSelection.reject)
        QtCore.QMetaObject.connectSlotsByName(spectrumParametersSelection)

    def retranslateUi(self, spectrumParametersSelection):
        _translate = QtCore.QCoreApplication.translate
        spectrumParametersSelection.setWindowTitle(_translate("spectrumParametersSelection", "spectrumParametersSelection"))
        self.fUnitsCombobox.setItemText(0, _translate("spectrumParametersSelection", "erg/s/cm2/um"))
        self.fUnitsCombobox.setItemText(1, _translate("spectrumParametersSelection", "Jy"))
        self.fUnitsCombobox.setItemText(2, _translate("spectrumParametersSelection", "mJy"))
        self.fUnitsCombobox.setItemText(3, _translate("spectrumParametersSelection", "uJy"))
        self.fUnitsCombobox.setItemText(4, _translate("spectrumParametersSelection", "W/m2/Hz"))
        self.fUnitsCombobox.setItemText(5, _translate("spectrumParametersSelection", "erg/s/cm2/Hz"))
        self.fUnitsCombobox.setItemText(6, _translate("spectrumParametersSelection", "W/m2/Angstroms"))
        self.fUnitsCombobox.setItemText(7, _translate("spectrumParametersSelection", "erg/s/cm2/Angstroms"))
        self.wUnitsCombobox.setItemText(0, _translate("spectrumParametersSelection", "um"))
        self.wUnitsCombobox.setItemText(1, _translate("spectrumParametersSelection", "angstroms"))
        self.wUnitsCombobox.setItemText(2, _translate("spectrumParametersSelection", "nm"))
        self.label_4.setText(_translate("spectrumParametersSelection", "Wavelength units"))
        self.label_5.setText(_translate("spectrumParametersSelection", "Flux units"))
        self.redshiftLineEdit.setPlaceholderText(_translate("spectrumParametersSelection", "0.0"))
        self.label_3.setText(_translate("spectrumParametersSelection", "Redshift"))
        self.label.setText(_translate("spectrumParametersSelection", "Spectrum from"))
        self.cancelButton.setText(_translate("spectrumParametersSelection", "Cancel"))
        self.acceptButton.setText(_translate("spectrumParametersSelection", "Accept"))

