# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mrs_chan.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MrsChanell(object):
    def setupUi(self, MrsChanell):
        MrsChanell.setObjectName("MrsChanell")
        MrsChanell.resize(826, 752)
        self.centralwidget = QtWidgets.QWidget(MrsChanell)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bottomPlot = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomPlot.sizePolicy().hasHeightForWidth())
        self.bottomPlot.setSizePolicy(sizePolicy)
        self.bottomPlot.setMinimumSize(QtCore.QSize(500, 500))
        self.bottomPlot.setTitle("")
        self.bottomPlot.setObjectName("bottomPlot")
        self.gridLayout.addWidget(self.bottomPlot, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.channellEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.channellEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.channellEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.channellEdit.setReadOnly(True)
        self.channellEdit.setObjectName("channellEdit")
        self.horizontalLayout_3.addWidget(self.channellEdit)
        self.lambdaObsLabel = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lambdaObsLabel.sizePolicy().hasHeightForWidth())
        self.lambdaObsLabel.setSizePolicy(sizePolicy)
        self.lambdaObsLabel.setObjectName("lambdaObsLabel")
        self.horizontalLayout_3.addWidget(self.lambdaObsLabel)
        self.lambdaObsEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lambdaObsEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lambdaObsEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lambdaObsEdit.setReadOnly(True)
        self.lambdaObsEdit.setObjectName("lambdaObsEdit")
        self.horizontalLayout_3.addWidget(self.lambdaObsEdit)
        self.lambdaObsUnitLabel = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lambdaObsUnitLabel.sizePolicy().hasHeightForWidth())
        self.lambdaObsUnitLabel.setSizePolicy(sizePolicy)
        self.lambdaObsUnitLabel.setObjectName("lambdaObsUnitLabel")
        self.horizontalLayout_3.addWidget(self.lambdaObsUnitLabel)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lambdaLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lambdaLabel.sizePolicy().hasHeightForWidth())
        self.lambdaLabel.setSizePolicy(sizePolicy)
        self.lambdaLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lambdaLabel.setObjectName("lambdaLabel")
        self.horizontalLayout.addWidget(self.lambdaLabel)
        self.lambdaEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lambdaEdit.sizePolicy().hasHeightForWidth())
        self.lambdaEdit.setSizePolicy(sizePolicy)
        self.lambdaEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lambdaEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lambdaEdit.setObjectName("lambdaEdit")
        self.horizontalLayout.addWidget(self.lambdaEdit)
        self.lambdaUnitLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lambdaUnitLabel.sizePolicy().hasHeightForWidth())
        self.lambdaUnitLabel.setSizePolicy(sizePolicy)
        self.lambdaUnitLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lambdaUnitLabel.setObjectName("lambdaUnitLabel")
        self.horizontalLayout.addWidget(self.lambdaUnitLabel)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.zEdit = QtWidgets.QLineEdit(self.groupBox)
        self.zEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.zEdit.setObjectName("zEdit")
        self.horizontalLayout.addWidget(self.zEdit)
        self.channellButton = QtWidgets.QPushButton(self.groupBox)
        self.channellButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.channellButton.setObjectName("channellButton")
        self.horizontalLayout.addWidget(self.channellButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MrsChanell.setCentralWidget(self.centralwidget)

        self.retranslateUi(MrsChanell)
        QtCore.QMetaObject.connectSlotsByName(MrsChanell)

    def retranslateUi(self, MrsChanell):
        _translate = QtCore.QCoreApplication.translate
        MrsChanell.setWindowTitle(_translate("MrsChanell", "MrsChanell - Beta version"))
        self.groupBox_2.setTitle(_translate("MrsChanell", "Results"))
        self.label_4.setText(_translate("MrsChanell", "Channel:"))
        self.lambdaObsLabel.setText(_translate("MrsChanell", "TextLabel"))
        self.lambdaObsUnitLabel.setText(_translate("MrsChanell", "TextLabel"))
        self.lambdaLabel.setText(_translate("MrsChanell", "TextLabel"))
        self.lambdaUnitLabel.setText(_translate("MrsChanell", "TextLabel"))
        self.label_3.setText(_translate("MrsChanell", "z:"))
        self.channellButton.setText(_translate("MrsChanell", "Calculate"))
