# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'all_tools.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_all_tools(object):
    def setupUi(self, all_tools):
        all_tools.setObjectName("all_tools")
        all_tools.resize(825, 350)
        all_tools.setMaximumSize(QtCore.QSize(2000, 350))
        self.centralwidget = QtWidgets.QWidget(all_tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.mrsChanButton = QtWidgets.QPushButton(self.centralwidget)
        self.mrsChanButton.setObjectName("mrsChanButton")
        self.gridLayout.addWidget(self.mrsChanButton, 4, 0, 1, 1)
        self.mrsSpecChanButton = QtWidgets.QPushButton(self.centralwidget)
        self.mrsSpecChanButton.setObjectName("mrsSpecChanButton")
        self.gridLayout.addWidget(self.mrsSpecChanButton, 4, 1, 1, 1)
        self.mrsDetPlotButton = QtWidgets.QPushButton(self.centralwidget)
        self.mrsDetPlotButton.setObjectName("mrsDetPlotButton")
        self.gridLayout.addWidget(self.mrsDetPlotButton, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 50))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fitLineButton = QtWidgets.QPushButton(self.groupBox)
        self.fitLineButton.setObjectName("fitLineButton")
        self.gridLayout_3.addWidget(self.fitLineButton, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.cubeAnsButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cubeAnsButton.sizePolicy().hasHeightForWidth())
        self.cubeAnsButton.setSizePolicy(sizePolicy)
        self.cubeAnsButton.setObjectName("cubeAnsButton")
        self.gridLayout_3.addWidget(self.cubeAnsButton, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.subVizButton = QtWidgets.QPushButton(self.groupBox)
        self.subVizButton.setObjectName("subVizButton")
        self.gridLayout_3.addWidget(self.subVizButton, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        all_tools.setCentralWidget(self.centralwidget)

        self.retranslateUi(all_tools)
        QtCore.QMetaObject.connectSlotsByName(all_tools)

    def retranslateUi(self, all_tools):
        _translate = QtCore.QCoreApplication.translate
        all_tools.setWindowTitle(_translate("all_tools", "AllTools"))
        self.label_3.setText(_translate("all_tools", "Tool to visualize the relationship between emitted wavelength and density flux associate."))
        self.label_2.setText(_translate("all_tools", " Tool to identify wich channels from the MRS range, an emitted wavelenth is."))
        self.mrsChanButton.setText(_translate("all_tools", "mrs_chan"))
        self.mrsSpecChanButton.setText(_translate("all_tools", "mrs_spec_chan"))
        self.mrsDetPlotButton.setText(_translate("all_tools", "mrs_det_plot"))
        self.label_4.setText(_translate("all_tools", "Tool to manipulate astronomic images based of frame and integration values."))
        self.label.setText(_translate("all_tools", "Select tool to show"))
        self.label_5.setText(_translate("all_tools", "Tool to visualize multiple Gauss fitted models based on an spectrum."))
        self.fitLineButton.setText(_translate("all_tools", "fit_line"))
        self.label_6.setText(_translate("all_tools", "Tool to visualize and interact a single cube given a MIRI cube format"))
        self.cubeAnsButton.setText(_translate("all_tools", "cube_ans"))
        self.label_7.setText(_translate("all_tools", "Tool to visualize and interact with all 12 cubes from the MRS channels"))
        self.subVizButton.setText(_translate("all_tools", "sub_viz"))

