# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'all_tools.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_all_tools(object):
    def setupUi(self, all_tools):
        all_tools.setObjectName("all_tools")
        all_tools.resize(1000, 300)
        all_tools.setMinimumSize(QtCore.QSize(1000, 300))
        all_tools.setMaximumSize(QtCore.QSize(2000, 300))
        self.centralwidget = QtWidgets.QWidget(all_tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.mrsDetPlotButton = QtWidgets.QPushButton(self.centralwidget)
        self.mrsDetPlotButton.setObjectName("mrsDetPlotButton")
        self.gridLayout.addWidget(self.mrsDetPlotButton, 4, 0, 1, 1)
        self.fitLineButton = QtWidgets.QPushButton(self.centralwidget)
        self.fitLineButton.setObjectName("fitLineButton")
        self.gridLayout.addWidget(self.fitLineButton, 4, 1, 1, 1)
        self.mrsChanButton = QtWidgets.QPushButton(self.centralwidget)
        self.mrsChanButton.setObjectName("mrsChanButton")
        self.gridLayout.addWidget(self.mrsChanButton, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.mrsSpecChanButton = QtWidgets.QPushButton(self.centralwidget)
        self.mrsSpecChanButton.setObjectName("mrsSpecChanButton")
        self.gridLayout.addWidget(self.mrsSpecChanButton, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 50))
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 50))
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        all_tools.setCentralWidget(self.centralwidget)

        self.retranslateUi(all_tools)
        QtCore.QMetaObject.connectSlotsByName(all_tools)

    def retranslateUi(self, all_tools):
        _translate = QtCore.QCoreApplication.translate
        all_tools.setWindowTitle(_translate("all_tools", "AllTools"))
        self.label_2.setText(_translate("all_tools", " Tool that identify wich channels from the MRS range, an emitted wavelenth is."))
        self.label_3.setText(_translate("all_tools", "Tool that visualizate the relationship between emitted wavelength and density flux associate."))
        self.mrsDetPlotButton.setText(_translate("all_tools", "mrs_det_plot"))
        self.fitLineButton.setText(_translate("all_tools", "fit_line"))
        self.mrsChanButton.setText(_translate("all_tools", "mrs_chan"))
        self.label.setText(_translate("all_tools", "Select tool to show"))
        self.mrsSpecChanButton.setText(_translate("all_tools", "mrs_spec_chan"))
        self.label_4.setText(_translate("all_tools", "Tool that manipulate astronomic images based of frame and integration values."))
        self.label_5.setText(_translate("all_tools", "Tool that representate multiple gauss fitted models based on an spectrum."))
