# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectrumSelection.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_spectrumSelection(object):
    def setupUi(self, spectrumSelection):
        spectrumSelection.setObjectName("spectrumSelection")
        spectrumSelection.resize(500, 150)
        spectrumSelection.setMinimumSize(QtCore.QSize(500, 150))
        spectrumSelection.setMaximumSize(QtCore.QSize(500, 150))
        self.gridLayout_2 = QtWidgets.QGridLayout(spectrumSelection)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.fileButton = QtWidgets.QPushButton(spectrumSelection)
        self.fileButton.setObjectName("fileButton")
        self.gridLayout.addWidget(self.fileButton, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.pathLabel = QtWidgets.QLabel(spectrumSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLabel.sizePolicy().hasHeightForWidth())
        self.pathLabel.setSizePolicy(sizePolicy)
        self.pathLabel.setObjectName("pathLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pathLabel)
        self.pathInputLabel = QtWidgets.QLabel(spectrumSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathInputLabel.sizePolicy().hasHeightForWidth())
        self.pathInputLabel.setSizePolicy(sizePolicy)
        self.pathInputLabel.setText("")
        self.pathInputLabel.setObjectName("pathInputLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pathInputLabel)
        self.redshiftLabel = QtWidgets.QLabel(spectrumSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redshiftLabel.sizePolicy().hasHeightForWidth())
        self.redshiftLabel.setSizePolicy(sizePolicy)
        self.redshiftLabel.setObjectName("redshiftLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.redshiftLabel)
        self.redshiftLineEdit = QtWidgets.QLineEdit(spectrumSelection)
        self.redshiftLineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redshiftLineEdit.sizePolicy().hasHeightForWidth())
        self.redshiftLineEdit.setSizePolicy(sizePolicy)
        self.redshiftLineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.redshiftLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.redshiftLineEdit.setReadOnly(False)
        self.redshiftLineEdit.setObjectName("redshiftLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.redshiftLineEdit)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.acceptButton = QtWidgets.QPushButton(spectrumSelection)
        self.acceptButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acceptButton.sizePolicy().hasHeightForWidth())
        self.acceptButton.setSizePolicy(sizePolicy)
        self.acceptButton.setObjectName("acceptButton")
        self.horizontalLayout_2.addWidget(self.acceptButton)
        self.cancelButton = QtWidgets.QPushButton(spectrumSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(spectrumSelection)
        self.acceptButton.clicked.connect(spectrumSelection.accept)
        self.cancelButton.clicked.connect(spectrumSelection.reject)
        QtCore.QMetaObject.connectSlotsByName(spectrumSelection)

    def retranslateUi(self, spectrumSelection):
        _translate = QtCore.QCoreApplication.translate
        spectrumSelection.setWindowTitle(_translate("spectrumSelection", "spectrumSelection"))
        self.fileButton.setText(_translate("spectrumSelection", "Select File"))
        self.pathLabel.setText(_translate("spectrumSelection", "Path: "))
        self.redshiftLabel.setText(_translate("spectrumSelection", "Redshift: "))
        self.redshiftLineEdit.setPlaceholderText(_translate("spectrumSelection", "0.0"))
        self.acceptButton.setText(_translate("spectrumSelection", "Accept"))
        self.cancelButton.setText(_translate("spectrumSelection", "Cancel"))
