# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fit_line.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FitLine(object):
    def setupUi(self, FitLine):
        FitLine.setObjectName("FitLine")
        FitLine.resize(908, 830)
        self.centralwidget = QtWidgets.QWidget(FitLine)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(200, -1, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.modelSelectionLabel = QtWidgets.QLabel(self.centralwidget)
        self.modelSelectionLabel.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelSelectionLabel.sizePolicy().hasHeightForWidth())
        self.modelSelectionLabel.setSizePolicy(sizePolicy)
        self.modelSelectionLabel.setObjectName("modelSelectionLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.modelSelectionLabel)
        self.modelSelectionComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.modelSelectionComboBox.setEnabled(False)
        self.modelSelectionComboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.modelSelectionComboBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.modelSelectionComboBox.setObjectName("modelSelectionComboBox")
        self.modelSelectionComboBox.addItem("")
        self.modelSelectionComboBox.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.modelSelectionComboBox)
        self.gridLayout.addLayout(self.formLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.clickNormalButton = QtWidgets.QPushButton(self.centralwidget)
        self.clickNormalButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clickNormalButton.sizePolicy().hasHeightForWidth())
        self.clickNormalButton.setSizePolicy(sizePolicy)
        self.clickNormalButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.clickNormalButton.setCheckable(True)
        self.clickNormalButton.setAutoExclusive(True)
        self.clickNormalButton.setObjectName("clickNormalButton")
        self.horizontalLayout_4.addWidget(self.clickNormalButton)
        self.zoomButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomButton.sizePolicy().hasHeightForWidth())
        self.zoomButton.setSizePolicy(sizePolicy)
        self.zoomButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.zoomButton.setCheckable(True)
        self.zoomButton.setAutoExclusive(True)
        self.zoomButton.setObjectName("zoomButton")
        self.horizontalLayout_4.addWidget(self.zoomButton)
        self.panButton = QtWidgets.QPushButton(self.centralwidget)
        self.panButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panButton.sizePolicy().hasHeightForWidth())
        self.panButton.setSizePolicy(sizePolicy)
        self.panButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.panButton.setCheckable(True)
        self.panButton.setAutoExclusive(True)
        self.panButton.setObjectName("panButton")
        self.horizontalLayout_4.addWidget(self.panButton)
        self.zoomFitButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomFitButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomFitButton.sizePolicy().hasHeightForWidth())
        self.zoomFitButton.setSizePolicy(sizePolicy)
        self.zoomFitButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.zoomFitButton.setObjectName("zoomFitButton")
        self.horizontalLayout_4.addWidget(self.zoomFitButton)
        self.undoButton = QtWidgets.QPushButton(self.centralwidget)
        self.undoButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.undoButton.sizePolicy().hasHeightForWidth())
        self.undoButton.setSizePolicy(sizePolicy)
        self.undoButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.undoButton.setObjectName("undoButton")
        self.horizontalLayout_4.addWidget(self.undoButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.middlePlot = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middlePlot.sizePolicy().hasHeightForWidth())
        self.middlePlot.setSizePolicy(sizePolicy)
        self.middlePlot.setTitle("")
        self.middlePlot.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.middlePlot.setFlat(False)
        self.middlePlot.setObjectName("middlePlot")
        self.gridLayout.addWidget(self.middlePlot, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        self.clearLastButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearLastButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearLastButton.sizePolicy().hasHeightForWidth())
        self.clearLastButton.setSizePolicy(sizePolicy)
        self.clearLastButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.clearLastButton.setObjectName("clearLastButton")
        self.horizontalLayout.addWidget(self.clearLastButton)
        self.clearFittingButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearFittingButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearFittingButton.sizePolicy().hasHeightForWidth())
        self.clearFittingButton.setSizePolicy(sizePolicy)
        self.clearFittingButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.clearFittingButton.setObjectName("clearFittingButton")
        self.horizontalLayout.addWidget(self.clearFittingButton)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loadPltButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadPltButton.sizePolicy().hasHeightForWidth())
        self.loadPltButton.setSizePolicy(sizePolicy)
        self.loadPltButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.loadPltButton.setObjectName("loadPltButton")
        self.horizontalLayout_3.addWidget(self.loadPltButton)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_3.addWidget(self.saveButton)
        self.showPointsButton = QtWidgets.QPushButton(self.centralwidget)
        self.showPointsButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showPointsButton.sizePolicy().hasHeightForWidth())
        self.showPointsButton.setSizePolicy(sizePolicy)
        self.showPointsButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.showPointsButton.setObjectName("showPointsButton")
        self.horizontalLayout_3.addWidget(self.showPointsButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pointsGenerationButton = QtWidgets.QPushButton(self.centralwidget)
        self.pointsGenerationButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointsGenerationButton.sizePolicy().hasHeightForWidth())
        self.pointsGenerationButton.setSizePolicy(sizePolicy)
        self.pointsGenerationButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pointsGenerationButton.setObjectName("pointsGenerationButton")
        self.horizontalLayout_2.addWidget(self.pointsGenerationButton)
        self.indicationLabel = QtWidgets.QLabel(self.centralwidget)
        self.indicationLabel.setEnabled(True)
        self.indicationLabel.setMinimumSize(QtCore.QSize(400, 0))
        self.indicationLabel.setMaximumSize(QtCore.QSize(400, 16777215))
        self.indicationLabel.setText("")
        self.indicationLabel.setObjectName("indicationLabel")
        self.horizontalLayout_2.addWidget(self.indicationLabel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 2, 1, 1)
        FitLine.setCentralWidget(self.centralwidget)

        self.retranslateUi(FitLine)
        QtCore.QMetaObject.connectSlotsByName(FitLine)

    def retranslateUi(self, FitLine):
        _translate = QtCore.QCoreApplication.translate
        FitLine.setWindowTitle(_translate("FitLine", "FitLine"))
        self.modelSelectionLabel.setText(_translate("FitLine", "Choose model to be fitted"))
        self.modelSelectionComboBox.setItemText(0, _translate("FitLine", "One gaussian"))
        self.modelSelectionComboBox.setItemText(1, _translate("FitLine", "Two gaussians"))
        self.clickNormalButton.setText(_translate("FitLine", "Click"))
        self.zoomButton.setText(_translate("FitLine", "Zoom"))
        self.panButton.setText(_translate("FitLine", "Pan"))
        self.zoomFitButton.setText(_translate("FitLine", "Zoom fit"))
        self.undoButton.setText(_translate("FitLine", "Undo last zoom"))
        self.clearButton.setText(_translate("FitLine", "Clear all"))
        self.clearLastButton.setText(_translate("FitLine", "Clear last fitted model"))
        self.clearFittingButton.setText(_translate("FitLine", "Clear fitted models"))
        self.loadPltButton.setText(_translate("FitLine", "Load spectrum"))
        self.saveButton.setText(_translate("FitLine", "Save as png"))
        self.showPointsButton.setText(_translate("FitLine", "Show fitted data parameters"))
        self.pointsGenerationButton.setText(_translate("FitLine", "Mark points"))

