# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'collapsedWavelengthSelection.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_collapsedWavelengthSelection(object):
    def setupUi(self, collapsedWavelengthSelection):
        collapsedWavelengthSelection.setObjectName("collapsedWavelengthSelection")
        collapsedWavelengthSelection.resize(500, 150)
        collapsedWavelengthSelection.setMinimumSize(QtCore.QSize(500, 150))
        self.gridLayout_2 = QtWidgets.QGridLayout(collapsedWavelengthSelection)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.customWavelengthButton = QtWidgets.QPushButton(collapsedWavelengthSelection)
        self.customWavelengthButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.customWavelengthButton.setObjectName("customWavelengthButton")
        self.gridLayout.addWidget(self.customWavelengthButton, 4, 0, 1, 4)
        self.label = QtWidgets.QLabel(collapsedWavelengthSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.endRangeWavelengthLineEdit = QtWidgets.QLineEdit(collapsedWavelengthSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endRangeWavelengthLineEdit.sizePolicy().hasHeightForWidth())
        self.endRangeWavelengthLineEdit.setSizePolicy(sizePolicy)
        self.endRangeWavelengthLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.endRangeWavelengthLineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.endRangeWavelengthLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.endRangeWavelengthLineEdit.setObjectName("endRangeWavelengthLineEdit")
        self.gridLayout.addWidget(self.endRangeWavelengthLineEdit, 3, 2, 1, 2, QtCore.Qt.AlignHCenter)
        self.allWavelengthButton = QtWidgets.QPushButton(collapsedWavelengthSelection)
        self.allWavelengthButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.allWavelengthButton.setObjectName("allWavelengthButton")
        self.gridLayout.addWidget(self.allWavelengthButton, 1, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(collapsedWavelengthSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.initialRangeLabel = QtWidgets.QLabel(collapsedWavelengthSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.initialRangeLabel.sizePolicy().hasHeightForWidth())
        self.initialRangeLabel.setSizePolicy(sizePolicy)
        self.initialRangeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.initialRangeLabel.setObjectName("initialRangeLabel")
        self.gridLayout.addWidget(self.initialRangeLabel, 2, 0, 1, 2)
        self.endRangeLabel = QtWidgets.QLabel(collapsedWavelengthSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endRangeLabel.sizePolicy().hasHeightForWidth())
        self.endRangeLabel.setSizePolicy(sizePolicy)
        self.endRangeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.endRangeLabel.setObjectName("endRangeLabel")
        self.gridLayout.addWidget(self.endRangeLabel, 2, 2, 1, 2)
        self.initialRangeWavelengthLineEdit = QtWidgets.QLineEdit(collapsedWavelengthSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.initialRangeWavelengthLineEdit.sizePolicy().hasHeightForWidth())
        self.initialRangeWavelengthLineEdit.setSizePolicy(sizePolicy)
        self.initialRangeWavelengthLineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.initialRangeWavelengthLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.initialRangeWavelengthLineEdit.setClearButtonEnabled(False)
        self.initialRangeWavelengthLineEdit.setObjectName("initialRangeWavelengthLineEdit")
        self.gridLayout.addWidget(self.initialRangeWavelengthLineEdit, 3, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.endWavelengthLineEdit = QtWidgets.QLineEdit(collapsedWavelengthSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endWavelengthLineEdit.sizePolicy().hasHeightForWidth())
        self.endWavelengthLineEdit.setSizePolicy(sizePolicy)
        self.endWavelengthLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.endWavelengthLineEdit.setReadOnly(True)
        self.endWavelengthLineEdit.setObjectName("endWavelengthLineEdit")
        self.gridLayout.addWidget(self.endWavelengthLineEdit, 0, 3, 1, 1)
        self.initialWavelengthLineEdit = QtWidgets.QLineEdit(collapsedWavelengthSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.initialWavelengthLineEdit.sizePolicy().hasHeightForWidth())
        self.initialWavelengthLineEdit.setSizePolicy(sizePolicy)
        self.initialWavelengthLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.initialWavelengthLineEdit.setReadOnly(True)
        self.initialWavelengthLineEdit.setObjectName("initialWavelengthLineEdit")
        self.gridLayout.addWidget(self.initialWavelengthLineEdit, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 3, 1, 1)

        self.retranslateUi(collapsedWavelengthSelection)
        QtCore.QMetaObject.connectSlotsByName(collapsedWavelengthSelection)

    def retranslateUi(self, collapsedWavelengthSelection):
        _translate = QtCore.QCoreApplication.translate
        collapsedWavelengthSelection.setWindowTitle(_translate("collapsedWavelengthSelection", "collapsedWavelengthSelection"))
        self.customWavelengthButton.setText(_translate("collapsedWavelengthSelection", "Select range"))
        self.label.setText(_translate("collapsedWavelengthSelection", "Initial wavelength"))
        self.allWavelengthButton.setText(_translate("collapsedWavelengthSelection", "Select all wavelength range"))
        self.label_2.setText(_translate("collapsedWavelengthSelection", "End wavelength"))
        self.initialRangeLabel.setText(_translate("collapsedWavelengthSelection", "Initial Range"))
        self.endRangeLabel.setText(_translate("collapsedWavelengthSelection", "End Range"))

