# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ellipseCreation.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ellipseCreation(object):
    def setupUi(self, ellipseCreation):
        ellipseCreation.setObjectName("ellipseCreation")
        ellipseCreation.resize(600, 175)
        ellipseCreation.setMinimumSize(QtCore.QSize(600, 175))
        self.gridLayout_2 = QtWidgets.QGridLayout(ellipseCreation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.skyCoordInfoButton = QtWidgets.QPushButton(ellipseCreation)
        self.skyCoordInfoButton.setObjectName("skyCoordInfoButton")
        self.gridLayout.addWidget(self.skyCoordInfoButton, 4, 4, 1, 1)
        self.aAxisLineEdit = QtWidgets.QLineEdit(ellipseCreation)
        self.aAxisLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.aAxisLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.aAxisLineEdit.setObjectName("aAxisLineEdit")
        self.gridLayout.addWidget(self.aAxisLineEdit, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(ellipseCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.label_3 = QtWidgets.QLabel(ellipseCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(ellipseCreation)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.createButtonPixel = QtWidgets.QPushButton(ellipseCreation)
        self.createButtonPixel.setObjectName("createButtonPixel")
        self.gridLayout.addWidget(self.createButtonPixel, 3, 0, 1, 4)
        self.centerYLineEdit = QtWidgets.QLineEdit(ellipseCreation)
        self.centerYLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.centerYLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centerYLineEdit.setObjectName("centerYLineEdit")
        self.gridLayout.addWidget(self.centerYLineEdit, 1, 3, 1, 1)
        self.bAxisLineEdit = QtWidgets.QLineEdit(ellipseCreation)
        self.bAxisLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.bAxisLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bAxisLineEdit.setObjectName("bAxisLineEdit")
        self.gridLayout.addWidget(self.bAxisLineEdit, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(ellipseCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.centerXLineEdit = QtWidgets.QLineEdit(ellipseCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerXLineEdit.sizePolicy().hasHeightForWidth())
        self.centerXLineEdit.setSizePolicy(sizePolicy)
        self.centerXLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.centerXLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centerXLineEdit.setObjectName("centerXLineEdit")
        self.gridLayout.addWidget(self.centerXLineEdit, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(ellipseCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.createButtonCoord = QtWidgets.QPushButton(ellipseCreation)
        self.createButtonCoord.setObjectName("createButtonCoord")
        self.gridLayout.addWidget(self.createButtonCoord, 4, 0, 1, 4)
        self.pixelInfoButton = QtWidgets.QPushButton(ellipseCreation)
        self.pixelInfoButton.setObjectName("pixelInfoButton")
        self.gridLayout.addWidget(self.pixelInfoButton, 3, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(ellipseCreation)
        QtCore.QMetaObject.connectSlotsByName(ellipseCreation)

    def retranslateUi(self, ellipseCreation):
        _translate = QtCore.QCoreApplication.translate
        ellipseCreation.setWindowTitle(_translate("ellipseCreation", "ellipseCreation"))
        self.skyCoordInfoButton.setText(_translate("ellipseCreation", "Sky coordinate\n"
" format info"))
        self.label.setText(_translate("ellipseCreation", "Write the parameters to create the ellipse"))
        self.label_3.setText(_translate("ellipseCreation", "Axis a\n"
" (Major axis)\n"
" (In pixel or arcsec)"))
        self.label_5.setText(_translate("ellipseCreation", "Axis b\n"
" (Minor Axis)\n"
" (In pixel or arcsec)"))
        self.createButtonPixel.setText(_translate("ellipseCreation", "Create ellipse in pixels"))
        self.label_6.setText(_translate("ellipseCreation", "Center X or RA"))
        self.label_7.setText(_translate("ellipseCreation", "Center Y or DEC"))
        self.createButtonCoord.setText(_translate("ellipseCreation", "Create ellipse in coord"))
        self.pixelInfoButton.setText(_translate("ellipseCreation", "Pixel format info"))

