# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rectangleCreation.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_rectangleCreation(object):
    def setupUi(self, rectangleCreation):
        rectangleCreation.setObjectName("rectangleCreation")
        rectangleCreation.resize(600, 210)
        rectangleCreation.setMinimumSize(QtCore.QSize(600, 210))
        self.gridLayout_2 = QtWidgets.QGridLayout(rectangleCreation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.widthLineEdit = QtWidgets.QLineEdit(rectangleCreation)
        self.widthLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.widthLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widthLineEdit.setObjectName("widthLineEdit")
        self.gridLayout.addWidget(self.widthLineEdit, 3, 1, 1, 1)
        self.bottomLeftYLineEdit = QtWidgets.QLineEdit(rectangleCreation)
        self.bottomLeftYLineEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.bottomLeftYLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bottomLeftYLineEdit.setObjectName("bottomLeftYLineEdit")
        self.gridLayout.addWidget(self.bottomLeftYLineEdit, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(rectangleCreation)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.heightLineEdit = QtWidgets.QLineEdit(rectangleCreation)
        self.heightLineEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.heightLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.heightLineEdit.setObjectName("heightLineEdit")
        self.gridLayout.addWidget(self.heightLineEdit, 3, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(rectangleCreation)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 2, 1, 1)
        self.createBottomButtonPixel = QtWidgets.QPushButton(rectangleCreation)
        self.createBottomButtonPixel.setEnabled(True)
        self.createBottomButtonPixel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.createBottomButtonPixel.setObjectName("createBottomButtonPixel")
        self.gridLayout.addWidget(self.createBottomButtonPixel, 4, 2, 1, 2)
        self.centerYLineEdit = QtWidgets.QLineEdit(rectangleCreation)
        self.centerYLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.centerYLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centerYLineEdit.setObjectName("centerYLineEdit")
        self.gridLayout.addWidget(self.centerYLineEdit, 2, 1, 1, 1)
        self.createBottomButtonCoord = QtWidgets.QPushButton(rectangleCreation)
        self.createBottomButtonCoord.setObjectName("createBottomButtonCoord")
        self.gridLayout.addWidget(self.createBottomButtonCoord, 5, 2, 1, 2)
        self.label_2 = QtWidgets.QLabel(rectangleCreation)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.bottomLeftXLineEdit = QtWidgets.QLineEdit(rectangleCreation)
        self.bottomLeftXLineEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.bottomLeftXLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bottomLeftXLineEdit.setObjectName("bottomLeftXLineEdit")
        self.gridLayout.addWidget(self.bottomLeftXLineEdit, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(rectangleCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.centerXLineEdit = QtWidgets.QLineEdit(rectangleCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerXLineEdit.sizePolicy().hasHeightForWidth())
        self.centerXLineEdit.setSizePolicy(sizePolicy)
        self.centerXLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.centerXLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centerXLineEdit.setObjectName("centerXLineEdit")
        self.gridLayout.addWidget(self.centerXLineEdit, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(rectangleCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(rectangleCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(rectangleCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.createCenterButtonPixel = QtWidgets.QPushButton(rectangleCreation)
        self.createCenterButtonPixel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createCenterButtonPixel.sizePolicy().hasHeightForWidth())
        self.createCenterButtonPixel.setSizePolicy(sizePolicy)
        self.createCenterButtonPixel.setMinimumSize(QtCore.QSize(0, 0))
        self.createCenterButtonPixel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.createCenterButtonPixel.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.createCenterButtonPixel.setAcceptDrops(False)
        self.createCenterButtonPixel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.createCenterButtonPixel.setAutoFillBackground(False)
        self.createCenterButtonPixel.setDefault(False)
        self.createCenterButtonPixel.setFlat(False)
        self.createCenterButtonPixel.setObjectName("createCenterButtonPixel")
        self.gridLayout.addWidget(self.createCenterButtonPixel, 4, 0, 1, 2)
        self.skyCoordInfoButton = QtWidgets.QPushButton(rectangleCreation)
        self.skyCoordInfoButton.setObjectName("skyCoordInfoButton")
        self.gridLayout.addWidget(self.skyCoordInfoButton, 5, 4, 1, 1)
        self.createCenterButtonCoord = QtWidgets.QPushButton(rectangleCreation)
        self.createCenterButtonCoord.setObjectName("createCenterButtonCoord")
        self.gridLayout.addWidget(self.createCenterButtonCoord, 5, 0, 1, 2)
        self.pixelInfoButton = QtWidgets.QPushButton(rectangleCreation)
        self.pixelInfoButton.setObjectName("pixelInfoButton")
        self.gridLayout.addWidget(self.pixelInfoButton, 4, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(rectangleCreation)
        QtCore.QMetaObject.connectSlotsByName(rectangleCreation)

    def retranslateUi(self, rectangleCreation):
        _translate = QtCore.QCoreApplication.translate
        rectangleCreation.setWindowTitle(_translate("rectangleCreation", "rectangleCreation"))
        self.label_4.setText(_translate("rectangleCreation", "Bottom Left Y or DEC"))
        self.label_5.setText(_translate("rectangleCreation", "Height (pixel or arcsec)"))
        self.createBottomButtonPixel.setText(_translate("rectangleCreation", "Create rectangle \n"
"with bottom coordinates in pixels"))
        self.createBottomButtonCoord.setText(_translate("rectangleCreation", "Create rectangle \n"
"with bottom coordinates"))
        self.label_2.setText(_translate("rectangleCreation", "Bottom Left X or RA"))
        self.label.setText(_translate("rectangleCreation", "Write the parameters to create the rectangle"))
        self.label_7.setText(_translate("rectangleCreation", "Center Y or DEC"))
        self.label_3.setText(_translate("rectangleCreation", "Width (pixel or arcsec)"))
        self.label_6.setText(_translate("rectangleCreation", "Center X or RA"))
        self.createCenterButtonPixel.setText(_translate("rectangleCreation", "Create rectangle \n"
"with center coordinates in pixels"))
        self.skyCoordInfoButton.setText(_translate("rectangleCreation", "Sky coordinate\n"
" format info"))
        self.createCenterButtonCoord.setText(_translate("rectangleCreation", "Create rectangle \n"
"with center coordinates"))
        self.pixelInfoButton.setText(_translate("rectangleCreation", "Pixel format info"))

