# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sub_viz.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sub_viz(object):
    def setupUi(self, sub_viz):
        sub_viz.setObjectName("sub_viz")
        sub_viz.resize(1100, 800)
        sub_viz.setMinimumSize(QtCore.QSize(1100, 800))
        self.widget = QtWidgets.QWidget(sub_viz)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setVerticalSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sliceMaximumValue = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceMaximumValue.sizePolicy().hasHeightForWidth())
        self.sliceMaximumValue.setSizePolicy(sizePolicy)
        self.sliceMaximumValue.setText("")
        self.sliceMaximumValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sliceMaximumValue.setObjectName("sliceMaximumValue")
        self.gridLayout_3.addWidget(self.sliceMaximumValue, 0, 2, 1, 1)
        self.spaceCubePlot = QtWidgets.QGroupBox(self.widget)
        self.spaceCubePlot.setTitle("")
        self.spaceCubePlot.setObjectName("spaceCubePlot")
        self.gridLayout_3.addWidget(self.spaceCubePlot, 1, 0, 1, 3)
        self.sliceMinimumValue = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceMinimumValue.sizePolicy().hasHeightForWidth())
        self.sliceMinimumValue.setSizePolicy(sizePolicy)
        self.sliceMinimumValue.setText("")
        self.sliceMinimumValue.setObjectName("sliceMinimumValue")
        self.gridLayout_3.addWidget(self.sliceMinimumValue, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        sub_viz.setCentralWidget(self.widget)
        self.menuBar = QtWidgets.QMenuBar(sub_viz)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setEnabled(False)
        self.menuTools.setObjectName("menuTools")
        self.menuShow_figure = QtWidgets.QMenu(self.menuTools)
        self.menuShow_figure.setEnabled(False)
        self.menuShow_figure.setObjectName("menuShow_figure")
        sub_viz.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(sub_viz)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRectangle = QtWidgets.QAction(sub_viz)
        self.actionRectangle.setEnabled(True)
        self.actionRectangle.setObjectName("actionRectangle")
        self.actionZoom = QtWidgets.QAction(sub_viz)
        self.actionZoom.setEnabled(True)
        self.actionZoom.setObjectName("actionZoom")
        self.actionPan = QtWidgets.QAction(sub_viz)
        self.actionPan.setEnabled(True)
        self.actionPan.setObjectName("actionPan")
        self.actionMinMax_Interval = QtWidgets.QAction(sub_viz)
        self.actionMinMax_Interval.setObjectName("actionMinMax_Interval")
        self.actionZScale_Interval = QtWidgets.QAction(sub_viz)
        self.actionZScale_Interval.setObjectName("actionZScale_Interval")
        self.actionSqrt = QtWidgets.QAction(sub_viz)
        self.actionSqrt.setObjectName("actionSqrt")
        self.actionLog = QtWidgets.QAction(sub_viz)
        self.actionLog.setObjectName("actionLog")
        self.actionLinear = QtWidgets.QAction(sub_viz)
        self.actionLinear.setObjectName("actionLinear")
        self.actionGray = QtWidgets.QAction(sub_viz)
        self.actionGray.setObjectName("actionGray")
        self.actionAccent = QtWidgets.QAction(sub_viz)
        self.actionAccent.setObjectName("actionAccent")
        self.actionHeat = QtWidgets.QAction(sub_viz)
        self.actionHeat.setObjectName("actionHeat")
        self.actionRainbow = QtWidgets.QAction(sub_viz)
        self.actionRainbow.setObjectName("actionRainbow")
        self.actionCoolWarm = QtWidgets.QAction(sub_viz)
        self.actionCoolWarm.setObjectName("actionCoolWarm")
        self.actionRectangle_coordinates = QtWidgets.QAction(sub_viz)
        self.actionRectangle_coordinates.setEnabled(False)
        self.actionRectangle_coordinates.setObjectName("actionRectangle_coordinates")
        self.actionCreation_Rectangle = QtWidgets.QAction(sub_viz)
        self.actionCreation_Rectangle.setObjectName("actionCreation_Rectangle")
        self.actionSpectrum_visualization = QtWidgets.QAction(sub_viz)
        self.actionSpectrum_visualization.setObjectName("actionSpectrum_visualization")
        self.actionEllipse = QtWidgets.QAction(sub_viz)
        self.actionEllipse.setObjectName("actionEllipse")
        self.actionBackground_subtraction = QtWidgets.QAction(sub_viz)
        self.actionBackground_subtraction.setEnabled(False)
        self.actionBackground_subtraction.setObjectName("actionBackground_subtraction")
        self.actionUnselect = QtWidgets.QAction(sub_viz)
        self.actionUnselect.setObjectName("actionUnselect")
        self.actionCreation_Ellipse = QtWidgets.QAction(sub_viz)
        self.actionCreation_Ellipse.setObjectName("actionCreation_Ellipse")
        self.actionInteractiveOp = QtWidgets.QAction(sub_viz)
        self.actionInteractiveOp.setObjectName("actionInteractiveOp")
        self.actionApply_style = QtWidgets.QAction(sub_viz)
        self.actionApply_style.setObjectName("actionApply_style")
        self.actionManage_style = QtWidgets.QAction(sub_viz)
        self.actionManage_style.setObjectName("actionManage_style")
        self.actionSet_current_wavelength = QtWidgets.QAction(sub_viz)
        self.actionSet_current_wavelength.setObjectName("actionSet_current_wavelength")
        self.actionDrawRectangle = QtWidgets.QAction(sub_viz)
        self.actionDrawRectangle.setEnabled(False)
        self.actionDrawRectangle.setObjectName("actionDrawRectangle")
        self.actionDrawEllipse = QtWidgets.QAction(sub_viz)
        self.actionDrawEllipse.setEnabled(False)
        self.actionDrawEllipse.setObjectName("actionDrawEllipse")
        self.actionSavespng = QtWidgets.QAction(sub_viz)
        self.actionSavespng.setEnabled(False)
        self.actionSavespng.setObjectName("actionSavespng")
        self.actionEllipse_coordinates = QtWidgets.QAction(sub_viz)
        self.actionEllipse_coordinates.setEnabled(False)
        self.actionEllipse_coordinates.setObjectName("actionEllipse_coordinates")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSavespng)
        self.menuShow_figure.addAction(self.actionDrawRectangle)
        self.menuShow_figure.addAction(self.actionDrawEllipse)
        self.menuTools.addAction(self.actionSet_current_wavelength)
        self.menuTools.addAction(self.actionRectangle)
        self.menuTools.addAction(self.actionEllipse)
        self.menuTools.addAction(self.actionInteractiveOp)
        self.menuTools.addAction(self.actionManage_style)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionRectangle_coordinates)
        self.menuTools.addAction(self.actionCreation_Rectangle)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionEllipse_coordinates)
        self.menuTools.addAction(self.actionCreation_Ellipse)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionSpectrum_visualization)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionBackground_subtraction)
        self.menuTools.addAction(self.menuShow_figure.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())

        self.retranslateUi(sub_viz)
        QtCore.QMetaObject.connectSlotsByName(sub_viz)

    def retranslateUi(self, sub_viz):
        _translate = QtCore.QCoreApplication.translate
        sub_viz.setWindowTitle(_translate("sub_viz", "sub_viz"))
        self.menuFile.setTitle(_translate("sub_viz", "File"))
        self.menuTools.setTitle(_translate("sub_viz", "Tools"))
        self.menuShow_figure.setTitle(_translate("sub_viz", "Show figure"))
        self.actionOpen.setText(_translate("sub_viz", "Open"))
        self.actionRectangle.setText(_translate("sub_viz", "Rectangle"))
        self.actionZoom.setText(_translate("sub_viz", "Zoom"))
        self.actionPan.setText(_translate("sub_viz", "Pan"))
        self.actionMinMax_Interval.setText(_translate("sub_viz", "MinMax Interval"))
        self.actionZScale_Interval.setText(_translate("sub_viz", "ZScale Interval"))
        self.actionSqrt.setText(_translate("sub_viz", "Sqrt"))
        self.actionLog.setText(_translate("sub_viz", "Log"))
        self.actionLinear.setText(_translate("sub_viz", "Linear"))
        self.actionGray.setText(_translate("sub_viz", "Gray"))
        self.actionAccent.setText(_translate("sub_viz", "Accent"))
        self.actionHeat.setText(_translate("sub_viz", "Heat"))
        self.actionRainbow.setText(_translate("sub_viz", "Rainbow"))
        self.actionCoolWarm.setText(_translate("sub_viz", "CoolWarm"))
        self.actionRectangle_coordinates.setText(_translate("sub_viz", "Rectangle coordinates"))
        self.actionCreation_Rectangle.setText(_translate("sub_viz", "Creation of Rectangle parameterized"))
        self.actionSpectrum_visualization.setText(_translate("sub_viz", "Spectrum visualization"))
        self.actionEllipse.setText(_translate("sub_viz", "Ellipse"))
        self.actionBackground_subtraction.setText(_translate("sub_viz", "Background subtraction"))
        self.actionUnselect.setText(_translate("sub_viz", "Unselect current tool"))
        self.actionCreation_Ellipse.setText(_translate("sub_viz", "Creation of Ellipse parameterized"))
        self.actionInteractiveOp.setText(_translate("sub_viz", "Interactive operations (zoom and pan)"))
        self.actionApply_style.setText(_translate("sub_viz", "Apply style "))
        self.actionManage_style.setText(_translate("sub_viz", "Manage style"))
        self.actionSet_current_wavelength.setText(_translate("sub_viz", "Set current wavelength"))
        self.actionDrawRectangle.setText(_translate("sub_viz", "Rectangle"))
        self.actionDrawEllipse.setText(_translate("sub_viz", "Ellipse"))
        self.actionSavespng.setText(_translate("sub_viz", "Saves as png"))
        self.actionEllipse_coordinates.setText(_translate("sub_viz", "Ellipse coordinates"))

