# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectrumVisualization.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_spectrumVisualization(object):
    def setupUi(self, spectrumVisualization):
        spectrumVisualization.setObjectName("spectrumVisualization")
        spectrumVisualization.resize(788, 581)
        self.gridLayout_2 = QtWidgets.QGridLayout(spectrumVisualization)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(spectrumVisualization)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.spectrumLayout_vbox = QtWidgets.QVBoxLayout()
        self.spectrumLayout_vbox.setObjectName("spectrumLayout_vbox")
        self.verticalLayout_2.addLayout(self.spectrumLayout_vbox)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 2)
        self.saveButton = QtWidgets.QPushButton(spectrumVisualization)
        self.saveButton.setEnabled(False)
        self.saveButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 5, 0, 1, 2)
        self.loadButton = QtWidgets.QPushButton(spectrumVisualization)
        self.loadButton.setEnabled(False)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout.addWidget(self.loadButton, 7, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.zoomButton = QtWidgets.QToolButton(spectrumVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomButton.sizePolicy().hasHeightForWidth())
        self.zoomButton.setSizePolicy(sizePolicy)
        self.zoomButton.setCheckable(False)
        self.zoomButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.zoomButton.setObjectName("zoomButton")
        self.horizontalLayout_2.addWidget(self.zoomButton)
        self.panButton = QtWidgets.QToolButton(spectrumVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panButton.sizePolicy().hasHeightForWidth())
        self.panButton.setSizePolicy(sizePolicy)
        self.panButton.setCheckable(False)
        self.panButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.panButton.setObjectName("panButton")
        self.horizontalLayout_2.addWidget(self.panButton)
        self.zoomResetButton = QtWidgets.QPushButton(spectrumVisualization)
        self.zoomResetButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomResetButton.sizePolicy().hasHeightForWidth())
        self.zoomResetButton.setSizePolicy(sizePolicy)
        self.zoomResetButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zoomResetButton.setObjectName("zoomResetButton")
        self.horizontalLayout_2.addWidget(self.zoomResetButton)
        self.selectLinesButton = QtWidgets.QPushButton(spectrumVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectLinesButton.sizePolicy().hasHeightForWidth())
        self.selectLinesButton.setSizePolicy(sizePolicy)
        self.selectLinesButton.setObjectName("selectLinesButton")
        self.horizontalLayout_2.addWidget(self.selectLinesButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.savePNGButton = QtWidgets.QPushButton(spectrumVisualization)
        self.savePNGButton.setEnabled(False)
        self.savePNGButton.setObjectName("savePNGButton")
        self.gridLayout.addWidget(self.savePNGButton, 6, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(spectrumVisualization)
        QtCore.QMetaObject.connectSlotsByName(spectrumVisualization)

    def retranslateUi(self, spectrumVisualization):
        _translate = QtCore.QCoreApplication.translate
        spectrumVisualization.setWindowTitle(_translate("spectrumVisualization", "spectrumVisualization"))
        self.saveButton.setText(_translate("spectrumVisualization", "Save spectra in txt"))
        self.loadButton.setText(_translate("spectrumVisualization", "Load spectra in FitLine"))
        self.zoomButton.setText(_translate("spectrumVisualization", "Zoom"))
        self.panButton.setText(_translate("spectrumVisualization", "Pan"))
        self.zoomResetButton.setText(_translate("spectrumVisualization", "Zoom reset"))
        self.selectLinesButton.setText(_translate("spectrumVisualization", "Select galaxy lines"))
        self.savePNGButton.setText(_translate("spectrumVisualization", "Save spectra as png"))

