# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'styleManager.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_styleManager(object):
    def setupUi(self, styleManager):
        styleManager.setObjectName("styleManager")
        styleManager.resize(400, 105)
        self.gridLayout_2 = QtWidgets.QGridLayout(styleManager)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(styleManager)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.formLayout_3.setObjectName("formLayout_3")
        self.stretchLabel = QtWidgets.QLabel(styleManager)
        self.stretchLabel.setObjectName("stretchLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.stretchLabel)
        self.stretchComboBox = QtWidgets.QComboBox(styleManager)
        self.stretchComboBox.setObjectName("stretchComboBox")
        self.stretchComboBox.addItem("")
        self.stretchComboBox.addItem("")
        self.stretchComboBox.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stretchComboBox)
        self.gridLayout.addLayout(self.formLayout_3, 1, 2, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.formLayout.setObjectName("formLayout")
        self.colorLabel = QtWidgets.QLabel(styleManager)
        self.colorLabel.setObjectName("colorLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.colorLabel)
        self.colorComboBox = QtWidgets.QComboBox(styleManager)
        self.colorComboBox.setObjectName("colorComboBox")
        self.colorComboBox.addItem("")
        self.colorComboBox.addItem("")
        self.colorComboBox.addItem("")
        self.colorComboBox.addItem("")
        self.colorComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.colorComboBox)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.formLayout_4.setObjectName("formLayout_4")
        self.scaleLabel = QtWidgets.QLabel(styleManager)
        self.scaleLabel.setObjectName("scaleLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.scaleLabel)
        self.scaleComboBox = QtWidgets.QComboBox(styleManager)
        self.scaleComboBox.setObjectName("scaleComboBox")
        self.scaleComboBox.addItem("")
        self.scaleComboBox.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.scaleComboBox)
        self.gridLayout.addLayout(self.formLayout_4, 1, 1, 1, 1)
        self.subbandComboBox = QtWidgets.QComboBox(styleManager)
        self.subbandComboBox.setObjectName("subbandComboBox")
        self.subbandComboBox.addItem("")
        self.subbandComboBox.addItem("")
        self.subbandComboBox.addItem("")
        self.subbandComboBox.addItem("")
        self.subbandComboBox.addItem("")
        self.subbandComboBox.addItem("")
        self.subbandComboBox.addItem("")
        self.subbandComboBox.addItem("")
        self.subbandComboBox.addItem("")
        self.subbandComboBox.addItem("")
        self.subbandComboBox.addItem("")
        self.subbandComboBox.addItem("")
        self.subbandComboBox.addItem("")
        self.gridLayout.addWidget(self.subbandComboBox, 0, 1, 1, 1)
        self.allSubbandsCheckBox = QtWidgets.QCheckBox(styleManager)
        self.allSubbandsCheckBox.setObjectName("allSubbandsCheckBox")
        self.gridLayout.addWidget(self.allSubbandsCheckBox, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(styleManager)
        QtCore.QMetaObject.connectSlotsByName(styleManager)

    def retranslateUi(self, styleManager):
        _translate = QtCore.QCoreApplication.translate
        styleManager.setWindowTitle(_translate("styleManager", "styleManager"))
        self.label.setText(_translate("styleManager", "Subband selected"))
        self.stretchLabel.setText(_translate("styleManager", "Stretch"))
        self.stretchComboBox.setItemText(0, _translate("styleManager", "Linear"))
        self.stretchComboBox.setItemText(1, _translate("styleManager", "Sqrt"))
        self.stretchComboBox.setItemText(2, _translate("styleManager", "Log"))
        self.colorLabel.setText(_translate("styleManager", "Color"))
        self.colorComboBox.setItemText(0, _translate("styleManager", "Gray"))
        self.colorComboBox.setItemText(1, _translate("styleManager", "Accent"))
        self.colorComboBox.setItemText(2, _translate("styleManager", "Heat"))
        self.colorComboBox.setItemText(3, _translate("styleManager", "Rainbow"))
        self.colorComboBox.setItemText(4, _translate("styleManager", "CoolWarm"))
        self.scaleLabel.setText(_translate("styleManager", "Scale"))
        self.scaleComboBox.setItemText(0, _translate("styleManager", "MinMax"))
        self.scaleComboBox.setItemText(1, _translate("styleManager", "ZScale"))
        self.subbandComboBox.setItemText(0, _translate("styleManager", "Select subband"))
        self.subbandComboBox.setItemText(1, _translate("styleManager", "1 Short"))
        self.subbandComboBox.setItemText(2, _translate("styleManager", "1 Medium"))
        self.subbandComboBox.setItemText(3, _translate("styleManager", "1 Long"))
        self.subbandComboBox.setItemText(4, _translate("styleManager", "2 Short"))
        self.subbandComboBox.setItemText(5, _translate("styleManager", "2 Medium"))
        self.subbandComboBox.setItemText(6, _translate("styleManager", "2 Long"))
        self.subbandComboBox.setItemText(7, _translate("styleManager", "3 Short"))
        self.subbandComboBox.setItemText(8, _translate("styleManager", "3 Medium"))
        self.subbandComboBox.setItemText(9, _translate("styleManager", "3 Long"))
        self.subbandComboBox.setItemText(10, _translate("styleManager", "4 Short"))
        self.subbandComboBox.setItemText(11, _translate("styleManager", "4 Medium"))
        self.subbandComboBox.setItemText(12, _translate("styleManager", "4 Long"))
        self.allSubbandsCheckBox.setText(_translate("styleManager", "Select all subbands"))

